#!/bin/bash
#BBTools version 39.06
#The steps below recapitulate the output of RQCFilter2 when run like this:
#rqcfilter2.sh jni=t in=/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/rustem_storage/projects/4_breviate_nanopore_pta_sags/analyses/1_basecalling/blo.fastq.gz out=/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/rustem_storage/projects/4_breviate_nanopore_pta_sags/analyses/5_decontamination/blo_decontaminated.fastq.gz rna=f trimfragadapter=t qtrim=r trimq=6 maxns=1 maq=10 minlen=49 mlf=0.33 phix=t removehuman=t removedog=t removecat=t removemouse=t khist=t removemicrobes=t sketch=t kapa=t clumpify=t rqcfilterdata=/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/software/RQCFilterData/RQCFilterData barcodefilter=f trimpolyg=5 threads=16
#Data dependencies are available at http://portal.nersc.gov/dna/microbial/assembly/bushnell/RQCFilterData.tar


sendsketch.sh in=/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/rustem_storage/projects/4_breviate_nanopore_pta_sags/analyses/1_basecalling/blo.fastq.gz out=sketch.txt reads=2000000 name=/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/rustem_storage/projects/4_breviate_nanopore_pta_sags/analyses/1_basecalling/blo.fastq.gz fname=/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/rustem_storage/projects/4_breviate_nanopore_pta_sags/analyses/1_basecalling/blo.fastq.gz minprob=0.2 samplerate=1.0 merge printname0=f records=20 color=false depth depth2 unique2 unique3 volume sortbyvolume contam2=genus minprob=0.6 refhits nt translate=f sizemult=1.2 ow

sendsketch.sh in=/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/rustem_storage/projects/4_breviate_nanopore_pta_sags/analyses/1_basecalling/blo.fastq.gz out=sketch.txt reads=2000000 name=/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/rustem_storage/projects/4_breviate_nanopore_pta_sags/analyses/1_basecalling/blo.fastq.gz fname=/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/rustem_storage/projects/4_breviate_nanopore_pta_sags/analyses/1_basecalling/blo.fastq.gz minprob=0.2 samplerate=1.0 merge printname0=f records=20 color=false depth depth2 unique2 unique3 volume sortbyvolume contam2=genus minprob=0.6 refhits refseq translate=f sizemult=2.5 append

sendsketch.sh in=/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/rustem_storage/projects/4_breviate_nanopore_pta_sags/analyses/1_basecalling/blo.fastq.gz out=sketch.txt reads=2000000 name=/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/rustem_storage/projects/4_breviate_nanopore_pta_sags/analyses/1_basecalling/blo.fastq.gz fname=/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/rustem_storage/projects/4_breviate_nanopore_pta_sags/analyses/1_basecalling/blo.fastq.gz minprob=0.2 samplerate=1.0 merge printname0=f records=20 color=false depth depth2 unique2 unique3 volume sortbyvolume contam2=genus minprob=0.6 refhits silva translate=f local sizemult=1 minkeycount=2 append

sendsketch.sh in=/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/rustem_storage/projects/4_breviate_nanopore_pta_sags/analyses/1_basecalling/blo.fastq.gz out=sketch.txt reads=2000000 name=/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/rustem_storage/projects/4_breviate_nanopore_pta_sags/analyses/1_basecalling/blo.fastq.gz fname=/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/rustem_storage/projects/4_breviate_nanopore_pta_sags/analyses/1_basecalling/blo.fastq.gz minprob=0.2 samplerate=1.0 merge printname0=f records=20 color=false depth depth2 unique2 unique3 volume sortbyvolume contam2=genus minprob=0.6 refhits prokprot translate=t sizemult=2.2 append

bbmerge.sh overwrite=true in1=/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/rustem_storage/projects/4_breviate_nanopore_pta_sags/analyses/1_basecalling/blo.fastq.gz outa=adaptersDetected.fa reads=1m

clumpify.sh pigz=t unpigz=t zl=4 reorder in1=/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/rustem_storage/projects/4_breviate_nanopore_pta_sags/analyses/1_basecalling/blo.fastq.gz out1=/tmp/TEMP_CLUMP_774d2903d5fee3d8ec8947a5de0f3_blo_decontaminated.fastq.gz passes=1

bbduk.sh ktrim=r ordered minlen=49 minlenfraction=0.33 mink=11 tbo tpe rcomp=f overwrite=true k=23 hdist=1 hdist2=1 ftm=5 pratio=G,C plen=20 phist=phist.txt qhist=qhist.txt bhist=bhist.txt gchist=gchist.txt pigz=t unpigz=t zl=4 ow=true in1=/tmp/TEMP_CLUMP_774d2903d5fee3d8ec8947a5de0f3_blo_decontaminated.fastq.gz out1=/tmp/TEMP_TRIM_774d2903d5fee3d8ec8947a5de0f3_blo_decontaminated.fastq.gz rqc=hashmap outduk=ktrim_kmerStats1.txt stats=ktrim_scaffoldStats1.txt loglog loglogout ref=/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/software/RQCFilterData/RQCFilterData/adapters2.fa.gz

rm /tmp/TEMP_CLUMP_774d2903d5fee3d8ec8947a5de0f3_blo_decontaminated.fastq.gz

seal.sh ordered overwrite=true k=31 hdist=0 pigz=t unpigz=t zl=6 in1=/tmp/TEMP_TRIM_774d2903d5fee3d8ec8947a5de0f3_blo_decontaminated.fastq.gz outu1=/tmp/TEMP_SPIKEIN_774d2903d5fee3d8ec8947a5de0f3_blo_decontaminated.fastq.gz outm=spikein.fq.gz stats=scaffoldStatsSpikein.txt loglog loglogout ref=/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/software/RQCFilterData/RQCFilterData/kapatags.L40.fa.gz

rm /tmp/TEMP_TRIM_774d2903d5fee3d8ec8947a5de0f3_blo_decontaminated.fastq.gz

bbduk.sh maq=10.0,0 trimq=6.0 qtrim=r ordered overwrite=true maxns=1 minlen=49 minlenfraction=0.33 k=31 hdist=1 pigz=t unpigz=t zl=6 cf=t barcodefilter=f ow=true in1=/tmp/TEMP_SPIKEIN_774d2903d5fee3d8ec8947a5de0f3_blo_decontaminated.fastq.gz out1=/tmp/TEMP_FILTER1_774d2903d5fee3d8ec8947a5de0f3_blo_decontaminated.fastq.gz outm=synth1.fq.gz rqc=hashmap outduk=kmerStats1.txt stats=scaffoldStats1.txt trimpolygleft=5 trimpolygright=5 loglog loglogout ref=/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/software/RQCFilterData/RQCFilterData/Illumina.artifacts.fa.gz,/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/software/RQCFilterData/RQCFilterData/nextera_LMP_linker.fa.gz,/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/software/RQCFilterData/RQCFilterData/phix174_ill.ref.fa.gz,/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/software/RQCFilterData/RQCFilterData/lambda.fa.gz,/cfs/klemming/projects/supr/tango2_lund_storage/nobackup/software/RQCFilterData/RQCFilterData/pJET1.2.fa.gz
